CREATE TABLE USER (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  USERNAME VARCHAR(32) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL ,
  ROLE ENUM('ROLE_DRIVER', 'ROLE_MANAGER') NOT NULL
)
  ENGINE = InnoDB;

INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('DRV-12345', '$2a$12$//0hyyCXAfAx91sOC0dft.AyCyV3CJYSUvIuvpzDJtZw3tKJf5tUS', 'ROLE_DRIVER');
INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('MGR-12345', '$2a$12$//0hyyCXAfAx91sOC0dft.AyCyV3CJYSUvIuvpzDJtZw3tKJf5tUS', 'ROLE_MANAGER');

CREATE TABLE CITY (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(127) NOT NULL UNIQUE ,
  COORDINATES_X INTEGER NOT NULL ,
  COORDINATES_Y INTEGER NOT NULL
#   ?DISTANCES?
)
  ENGINE = InnoDB;

CREATE TABLE TRUCK (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  REG_NUMBER VARCHAR(7) NOT NULL UNIQUE ,
  BRIGADE_STR INTEGER NOT NULL ,
  CAPACITY INTEGER NOT NULL ,
  STATE BOOLEAN NOT NULL DEFAULT TRUE ,
  CURRENT_CITY_ID INT NOT NULL ,
  FOREIGN KEY (CURRENT_CITY_ID) REFERENCES CITY (ID) ON UPDATE CASCADE
)
  ENGINE = InnoDB;

CREATE TABLE DRIVER (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  PERSONAL_NUMBER VARCHAR(9) NOT NULL UNIQUE ,
  NAME VARCHAR(127) NOT NULL ,
  SURNAME VARCHAR(127) NOT NULL ,
  WORKED_TIME INTEGER NOT NULL ,
  STATE ENUM('REST', 'ON_SHIFT', 'DRIVING', 'PORTER') NOT NULL ,
  CURRENT_CITY_ID INT ,
  CURRENT_TRUCK_ID INT ,

  FOREIGN KEY (CURRENT_CITY_ID) REFERENCES CITY (ID) ON UPDATE CASCADE ,
  FOREIGN KEY (CURRENT_TRUCK_ID) REFERENCES TRUCK (ID) ON UPDATE CASCADE
)
  ENGINE = InnoDB;

 CREATE TABLE CARGO (
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 CARGO_NUMBER VARCHAR(63) NOT NULL UNIQUE ,
 NAME VARCHAR(63) NOT NULL ,
 WEIGHT INTEGER NOT NULL ,
 STATE ENUM('PREPARED', 'ON_BOARD', 'DELIVERED', 'PORTER') NOT NULL
)
 ENGINE = InnoDB;

#
# # CREATE TABLE TRUCK_CITY (
# #   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
# #   TRUCK_ID INT NOT NULL ,
# #   CITY_ID INT NOT NULL ,
# #
# #   KEY 'TRUCK' ('TRUCK_ID') ,
# #   KEY 'CITY' ('CITY_ID') ,
# #
# #   CONSTRAINT 'TRUCK' FOREIGN KEY ('TRUCK_ID') REFERENCES 'TRUCK' ('ID') ON DELETE CASCADE ON UPDATE CASCADE ,
# #   CONSTRAINT 'CITY' FOREIGN KEY ('CITY_ID') REFERENCES 'CITY' ('ID') ON DELETE CASCADE ON UPDATE CASCADE
# # )
# #   ENGINE = INNODB;
#
#
# CREATE TABLE WAYPOINT (
#   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
#   CARGO INT NOT NULL ,
#   CITY INT NOT NULL ,
#   WP_TYPE ENUM('LOAD', 'UNLOAD') NOT NULL ,
#
#   FOREIGN KEY (CITY) REFERENCES CITY (ID) ,
#   FOREIGN KEY (CARGO) REFERENCES CARGO (ID) ,
#
#   UNIQUE (CITY, CARGO, WP_TYPE)
# )
#   ENGINE = InnoDB;
#
# CREATE TABLE DELIVERING_ORDER (
#   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
#   ORDER_NUMBER VARCHAR(63) NOT NULL UNIQUE ,
#   EXECUTED BOOLEAN NOT NULL DEFAULT FALSE ,
#   TRUCK INT NOT NULL ,
#
#   FOREIGN KEY (TRUCK) REFERENCES TRUCK (INT)
# )
#   ENGINE = InnoDB;
#
# # Table for mapping Deliver_Order and Driver
# CREATE TABLE ORDER_DRIVERS (
#   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
#   ORDER_NUMBER INT NOT NULL ,
#   PERSONAL_NUMBER INT NOT NULL ,
#
#   FOREIGN KEY (ORDER_NUMBER) REFERENCES DELIVERING_ORDER (ID) ,
#   FOREIGN KEY (PERSONAL_NUMBER) REFERENCES DRIVER (ID) ,
#
#   UNIQUE (ORDER_NUMBER, PERSONAL_NUMBER)
# )
#   ENGINE = InnoDB;
#
# # Table for mapping Deliver_Order and Waypoint
# CREATE TABLE ORDER_WAYPOINTS (
#   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
#   ORDER_NUMBER INT NOT NULL ,
#   WAYPOINT INT NOT NULL ,
#
#   FOREIGN KEY (ORDER_NUMBER) REFERENCES DELIVERING_ORDER (ID) ,
#   FOREIGN KEY (WAYPOINT) REFERENCES WAYPOINT (ID) ,
#
#   UNIQUE (ORDER_NUMBER, WAYPOINT)
# )
#   ENGINE = InnoDB;
#
# CREATE TABLE EMPLOYEE (
#   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
#   PERSONAL_NUMBER VARCHAR(15) NOT NULL UNIQUE ,
#   EMAIL VARCHAR(255) NOT NULL UNIQUE ,
#   NAME VARCHAR(127) NOT NULL ,
#   SURNAME VARCHAR(127) NOT NULL ,
#   PASSWORD VARCHAR(63) ,
#   CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE
#    ENUM
# )
#   ENGINE = InnoDB;

