
INSERT INTO city (NAME, COORDINATES_X, COORDINATES_Y, CITY_INDEX) VALUES ('Velikie_Luki', 128, 128, 'VLK');
INSERT INTO city (NAME, COORDINATES_X, COORDINATES_Y, CITY_INDEX) VALUES ('Moscow', 512, 512, 'MSK');
INSERT INTO city (NAME, COORDINATES_X, COORDINATES_Y, CITY_INDEX) VALUES ('Piter', 256, 256, 'SPB');

INSERT INTO user (USERNAME, PASSWORD, ROLE, EMAIL) VALUES ('MGR-123', '$2a$12$ct0FXevB.HXS4WVOjK1N3eBXYtuppH8q.54WmMa/3UKSg2.mT4TGi', 'ROLE_MANAGER', 'gaffstranger@gmail.com');
INSERT INTO user (USERNAME, PASSWORD, ROLE, EMAIL) VALUES ('WHM-123', '$2a$12$ct0FXevB.HXS4WVOjK1N3eBXYtuppH8q.54WmMa/3UKSg2.mT4TGi', 'ROLE_WAREHOUSEMAN', 'gaffstranger@gmail.com');
INSERT INTO user (USERNAME, PASSWORD, ROLE, EMAIL) VALUES ('RSM-123', '$2a$12$ct0FXevB.HXS4WVOjK1N3eBXYtuppH8q.54WmMa/3UKSg2.mT4TGi', 'ROLE_RESOURCE', 'gaffstranger@gmail.com');
